version: '3.3'

services:
  app:
    build: .
    image: python-training
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    ports:
      - 8001:8001
    volumes:
      - .:/app
    restart: always
    networks:
      - pythontraining

  database:
    image: postgres
    restart: always
    tty: true
    ports:
      - '${POSTGRES_PORT:-5432}:5432'
    environment:
      POSTGRES_PASSWORD: '${POSTGRES_PASSWORD}'
      POSTGRES_USER: '${POSTGRES_USER}'
      POSTGRES_DB: '${POSTGRES_DB}'
    volumes:
      - 'database:/var/lib/postgresql/data'
    networks:
      - pythontraining

  jupyter:
      image: jupyter/minimal-notebook
      volumes:
        - ./notebooks:/home/jovyan/work
      ports:
        - 8888:8888
      container_name: jupyter_notebook

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: '${PGADMIN_EMAIL}'
      PGADMIN_DEFAULT_PASSWORD: '${POSTGRES_PASSWORD}'
    ports:
      - 5050:80
    networks:
      - pythontraining
    depends_on:
      - database

networks:
  pythontraining:
    driver: bridge

volumes:
  database:
    driver: local
